print("");
print("PYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPY");
print("READ TWO TWO-DIGIT INTEGERS AND DETERMINE IF THE SUM OF BOTH INTEGERS PRODUCE AN EVEN NUMBER");
print("PYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPYPY");
print("");

num1 = int(input("write the first integer: "));
num2 = int(input("write the second integer: "));

if(num1 < 0):
    num1 *= -1;

if(num2 < 0):
    num2 *= -1;

sum = num1 + num2;

if(sum % 2 == 0):
    print("THE SUM OF BOTH INTEGERS (", sum, ") PRODUCES AN EVEN NUMBER");
else:
    print("THE SUM OF BOTH INTEGERS (", sum, ") DOESN'T PRODUCE AN EVEN NUMBER");